---
abstract: 'proxy requests and replace by local file'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-CocProxy
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Twiggy: 0
requires:
  Filter::Util::Call: 0
  Plack: 0
  Plack::App::File: 0
  Plack::App::Proxy: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Plack-App-CocProxy.git
version: 0.01
